### ISSUE TITLE
Write permissions of shared /Download folder

### ISSUE THREAD

**Issue by jumin94** [eliocamp/cimadata#1]
While trying to download data in the shared data folder I get the following error: 

cannot open file '/datos/CMIP6/Download/Format/Scripts_used/historical/...sh': Permission denied
 
This happened because the Download folder in /datos/CMIP6 belongs to the user who first downloaded data here. Could we change the write permissions of the folders so that they are open to everyone once we create them?

**Comment by eliocamp** [comment]
Subí una nueva versión con la posibilidad de setear los permisos por default de creación de carpetas y archivos (usando [umask](https://www.cyberciti.biz/tips/understanding-linux-unix-umask-value-usage.html)). Lo que hay que hacer es, antes de descargar nada, setear los permisos con:

```r
cmip_folder_set(CMIP_dir, mode = "shared")
```

Eso setea el modo por default. El argumento `mode` puede ser algo reconocido por umask o, màs fácil, "shared" o "private" que significa respectivamente, todos los permisos para todos y ningún permiso para par nadie.

Para actualizar, hay que instalar la nueva versión con: 

```r
devtools::install_github("eliocamp/cimadata")
```
